# Generated by Django 4.2.30 on 2026-05-13 19:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('minimum_age', models.IntegerField()),
                ('source_platform', models.CharField(blank=True, default='', max_length=64)),
                ('external_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sync_external_ref', models.CharField(blank=True, db_index=True, max_length=320, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentConsumer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('source_platform', models.CharField(blank=True, default='', max_length=64)),
                ('external_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('source_platform', models.CharField(blank=True, default='', max_length=64)),
                ('external_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_platform', models.CharField(blank=True, default='', max_length=64)),
                ('external_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incidence_type', models.CharField(choices=[('technical', 'Technical issue'), ('billing', 'Billing issue'), ('access', 'Access/login issue'), ('content', 'Content mismatch'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('source_platform', models.CharField(blank=True, default='', max_length=64)),
                ('external_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ss.content')),
                ('year', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('ss.content',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ss.content')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('total_seasons', models.IntegerField()),
            ],
            bases=('ss.content',),
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='ss.content')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visualizations', to='ss.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visualizations', to='ss.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ss.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlataformManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_managers', to='ss.platform')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_language_platform_extid'),
        ),
        migrations.AddField(
            model_name='incidence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_genre_platform_extid'),
        ),
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ss.country'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_country_platform_extid'),
        ),
        migrations.AddField(
            model_name='contentconsumer',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_consumers', to='ss.genre'),
        ),
        migrations.AddField(
            model_name='content',
            name='age_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.agerating'),
        ),
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.country'),
        ),
        migrations.AddField(
            model_name='content',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.director'),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.genre'),
        ),
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.language'),
        ),
        migrations.AddField(
            model_name='content',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='contents', to='ss.platform'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='ss.platform'),
        ),
        migrations.AddConstraint(
            model_name='agerating',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_agerating_platform_extid'),
        ),
        migrations.AddConstraint(
            model_name='visualization',
            constraint=models.UniqueConstraint(fields=('user', 'viewed_at'), name='unique_user_viewed_at'),
        ),
        migrations.AddConstraint(
            model_name='director',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_director_platform_extid'),
        ),
    ]
