# Generated by Django 4.2.30 on 2026-04-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('minimum_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ss.country')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('total_seasons', models.IntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.agerating')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.country')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.language')),
                ('platforms', models.ManyToManyField(blank=True, related_name='series', to='ss.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.agerating')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.country')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ss.language')),
                ('platforms', models.ManyToManyField(blank=True, related_name='movies', to='ss.platform')),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='ss.platform')),
            ],
        ),
    ]
