# Generated by Django 4.2.30 on 2026-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendent'), ('resolved', 'Resolta')], default='pending', max_length=20),
        ),
    ]
