# Generated by Django 4.2.30 on 2026-05-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0002_remove_notification_user_notification_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerating',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agerating',
            name='source_platform',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='content',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='sync_external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=320, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='source_platform',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='director',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='source_platform',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='genre',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='source_platform',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='language',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='source_platform',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='agerating',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_agerating_platform_extid'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_country_platform_extid'),
        ),
        migrations.AddConstraint(
            model_name='director',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_director_platform_extid'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_genre_platform_extid'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_platform', 'external_id'), name='uniq_ss_language_platform_extid'),
        ),
    ]
