# Generated by Django 4.2.30 on 2026-04-09 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ss', '0002_alter_agerating_id_alter_apikey_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_genres', models.ManyToManyField(blank=True, related_name='preferred_by_consumers', to='ss.genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_consumer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
