# Generated by Django 4.2.30 on 2026-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0003_catalog_mirror_nested_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
